export const models = [
  {
    id: 18,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "moestuin.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 90, max: 110 },
      rotation: { min: 0, max: 360 },
      spread: 25,
      offset: 0,
      margin: 15,
      children: {
        "moestuin-item1": {
          model: "moestuin-1.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 1000, y: 1000, z: 1000 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "moestuin-item2": {
          model: "moestuin-2.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 1000, y: 1000, z: 1000 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "moestuin-item3": {
          model: "moestuin-3.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 1000, y: 1000, z: 1000 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 75,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bordermix.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 14,
      offset: 5,
      children: {
        "bordermix-item1": {
          model: "bordermix.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 25, y: 25, z: 25 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 78,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "plantenmix.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 90, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 14,
      offset: 5,
      children: {
        "planten-mix-item1": {
          model: "plantenmix.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 25, y: 25, z: 25 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "planten-mix-item2": {
          model: "plantenmix.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 25, y: 25, z: 25 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 79,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixdonker.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 14,
      offset: 5,
      children: {
        "bloemen-mix-donker-item1": {
          model: "bloemenmixdonker-blue.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 35, y: 35, z: 35 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-donker-item2": {
          model: "bloemenmixdonker-red.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 35, y: 35, z: 35 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-donker-item3": {
          model: "bloemenmixdonker-purple.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 35, y: 35, z: 35 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 80,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmix.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 14,
      offset: 5,
      children: {
        "bloemen-mix-item1": {
          model: "bloemenmix-blue.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-licht-item2": {
          model: "bloemenmix-red.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item3": {
          model: "bloemenmix-white.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 81,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 14,
      offset: 5,
      children: {
        "bloemen-mix-licht-item1": {
          model: "bloemenmix-blue.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 35, y: 35, z: 35 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-licht-item2": {
          model: "bloemenmix-red.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 35, y: 35, z: 35 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-licht-item3": {
          model: "bloemenmix-white.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 35, y: 35, z: 35 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 225,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "border_tulpen.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 90, max: 110 },
      rotation: { min: 0, max: 360 },
      spread: 7,
      offset: 5,
      children: {
        "tulpen-short": {
          model: "tulpen-short.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 40, y: 40, z: 40 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "tulpen-mid": {
          model: "tulpen-mid.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 40, y: 40, z: 40 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "tulpen-tall": {
          model: "tulpen-tall.1.glb",
          type3d: "Collada",
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { x: 14.740742285579746, y: 9.362998454330038, z: 47.2713183493033 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 226,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "border_anemoon.jpg",
      textureScale: 40,
      layer: 2,
      scale: { min: 90, max: 110 },
      rotation: { min: 0, max: 360 },
      spread: 7,
      offset: 5,
      children: {
        "anemonen-short": {
          model: "anemoon-short.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 30, y: 30, z: 30 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "anemonen-mid": {
          model: "anemoon-mid.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 40, y: 40, z: 40 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "anemonen-tall": {
          model: "anemoon-tall.1.glb",
          type3d: "Collada",
          scale: { x: 100, y: 100, z: 100 },
          dimensions: { x: 8.778189142391351, y: 8.13076228818232, z: 19.56797597610022 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 227,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "border_ereprijs.jpg",
      textureScale: 40,
      layer: 2,
      scale: { min: 90, max: 110 },
      rotation: { min: 0, max: 360 },
      spread: 9,
      offset: 5,
      children: {
        "ereprijs-short": {
          model: "ereprijs-short.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 30, y: 30, z: 30 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "ereprijs-mid": {
          model: "ereprijs-mid.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 40, y: 40, z: 40 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "ereprijs-tall": {
          model: "ereprijs-tall.1.glb",
          type3d: "Collada",
          scale: { x: 50, y: 50, z: 50 },
          dimensions: {
            x: 19.773761858591875,
            y: 13.047015349253606,
            z: 34.19742940649165,
          },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 228,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "border_geranium.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 90, max: 110 },
      rotation: { min: 0, max: 360 },
      spread: 9,
      offset: 5,
      children: {
        "geranium-short": {
          model: "geranium-short.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 30, y: 30, z: 30 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "geranium-mid": {
          model: "geranium-mid.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 30, y: 30, z: 30 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "geranium-tall": {
          model: "geranium-tall.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 30, y: 30, z: 30 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 229,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "border_lavendel.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 90, max: 110 },
      rotation: { min: 0, max: 360 },
      spread: 5,
      offset: 5,
      children: {
        "lavendel-short": {
          model: "lavendel-short.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 30, y: 30, z: 30 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "lavendel-mid": {
          model: "lavendel-mid.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 30, y: 30, z: 30 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "lavendel-tall": {
          model: "lavendel-tall.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 30, y: 30, z: 30 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 230,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "border_violen.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 90, max: 110 },
      rotation: { min: 0, max: 360 },
      spread: 7,
      offset: 5,
      children: {
        "violen-short": {
          model: "violen-short.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 75, y: 75, z: 75 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "violen-mid": {
          model: "violen-mid.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 75, y: 75, z: 75 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "violen-tall": {
          model: "violen-tall.1.glb",
          type3d: "Collada",
          scale: { x: 100, y: 100, z: 100 },
          dimensions: { x: 13.839436131854388, y: 9.492744309033533, z: 44.09940898880478 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 844,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 9,
      offset: 7,
      children: {
        "bloemen-mix-item1": {
          model: "ereprijs-los-wit.1.glb",
          type3d: "Collada",
          scale: { x: 100, y: 100, z: 100 },
          dimensions: {
            x: 12.202316972643715,
            y: 12.836749395200389,
            z: 32.79235092615504,
          },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 848,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 5,
      offset: 5,
      children: {
        "bloemen-mix-item1": {
          model: "lavendel-los-groen.1.glb",
          type3d: "Collada",
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { x: 3.280102001215125, y: 5.740178502126469, z: 38.49890493546549 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 849,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 5,
      offset: 5,
      children: {
        "bloemen-mix-item1": {
          model: "lavendel-los-lichtblauw.1.glb",
          type3d: "Collada",
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { x: 3.280102001215125, y: 5.740178502126469, z: 38.49890493546549 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 851,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 5,
      offset: 5,
      children: {
        "bloemen-mix-item1": {
          model: "lavendel-los-rood.1.glb",
          type3d: "Collada",
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { x: 3.280102001215125, y: 5.740178502126469, z: 38.49890493546549 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 852,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 7,
      offset: 5,
      children: {
        "bloemen-mix-item1": {
          model: "tulpen-los-klein-blauwgroen.1.glb",
          type3d: "Collada",
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { x: 12.53883130586912, y: 6.981878216461785, z: 41.76636530731156 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item2": {
          model: "tulpen-los-groot-blauwgroen.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 853,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 7,
      offset: 5,
      children: {
        "bloemen-mix-item1": {
          model: "tulpen-los-klein-blauwpaars.1.glb",
          type3d: "Collada",
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { x: 12.53883130586912, y: 6.981878216461785, z: 41.76636530731156 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item2": {
          model: "tulpen-los-groot-blauwpaars.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 854,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 7,
      offset: 5,
      children: {
        "bloemen-mix-item1": {
          model: "tulpen-los-klein-roodgeel.1.glb",
          type3d: "Collada",
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { x: 12.53883130586912, y: 6.981878216461785, z: 41.76636530731156 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item2": {
          model: "tulpen-los-groot-roodgeel.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 855,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 7,
      offset: 5,
      children: {
        "bloemen-mix-item1": {
          model: "tulpen-los-klein-roodpaars.1.glb",
          type3d: "Collada",
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { x: 12.53883130586912, y: 6.981878216461785, z: 41.76636530731156 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item2": {
          model: "tulpen-los-groot-roodpaars.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 856,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 25,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 7,
      offset: 7,
      children: {
        "bloemen-mix-item1": {
          model: "violen-los-klein-blauwgroen.1.glb",
          type3d: "Collada",
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { x: 9.008565048285764, y: 8.713409628964444, z: 34.54372532557038 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item2": {
          model: "violen-los-middel-blauwgroen.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 25, y: 25, z: 25 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item3": {
          model: "violen-los-groot-blauwgroen.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 30, y: 30, z: 30 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 857,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 25,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 7,
      offset: 7,
      children: {
        "bloemen-mix-item1": {
          model: "violen-los-klein-geelrood.1.glb",
          type3d: "Collada",
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { x: 9.008565048285764, y: 8.713409628964444, z: 34.54372532557038 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item2": {
          model: "violen-los-middel-geelrood.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 25, y: 25, z: 25 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item3": {
          model: "violen-los-groot-geelrood.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 30, y: 30, z: 30 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 859,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 25,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 7,
      offset: 7,
      children: {
        "bloemen-mix-item1": {
          model: "violen-los-klein-paars.1.glb",
          type3d: "Collada",
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { x: 9.008565048285764, y: 8.713409628964444, z: 34.54372532557038 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item2": {
          model: "violen-los-middel-paars.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 25, y: 25, z: 25 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item3": {
          model: "violen-los-groot-paars.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 30, y: 30, z: 30 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 860,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 25,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 7,
      offset: 7,
      children: {
        "bloemen-mix-item1": {
          model: "violen-los-klein-rood.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 25, y: 25, z: 25 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item2": {
          model: "violen-los-middel-rood.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 25, y: 25, z: 25 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item3": {
          model: "violen-los-groot-rood.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 30, y: 30, z: 30 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 931,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 4,
      offset: 16,
      children: {
        "bloemen-mix-item1": {
          model: "bloemen-los-klein-blauw.1.glb",
          type3d: "Collada",
          scale: { x: 100, y: 100, z: 100 },
          dimensions: {
            x: 7.0925188081066475,
            y: 5.571112667522148,
            z: 30.216048016335783,
          },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item2": {
          model: "bloemen-los-middel-blauw.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item3": {
          model: "bloemen-los-groot-blauw.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 933,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 4,
      offset: 16,
      children: {
        "bloemen-mix-item1": {
          model: "bloemen-los-klein.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item2": {
          model: "bloemen-los-middel.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item3": {
          model: "bloemen-los-groot.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 934,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 4,
      offset: 16,
      children: {
        "bloemen-mix-item1": {
          model: "bloemen-los-klein-rood.1.glb",
          type3d: "Collada",
          scale: { x: 100, y: 100, z: 100 },
          dimensions: {
            x: 7.0925188081066475,
            y: 5.571112667522148,
            z: 30.216048016335783,
          },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item2": {
          model: "bloemen-los-middel-rood.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item3": {
          model: "bloemen-los-groot-rood.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 935,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 4,
      offset: 16,
      children: {
        "bloemen-mix-item1": {
          model: "bloemen-los-klein-roze.1.glb",
          type3d: "Collada",
          scale: { x: 100, y: 100, z: 100 },
          dimensions: {
            x: 7.0925188081066475,
            y: 5.571112667522148,
            z: 30.216048016335783,
          },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item2": {
          model: "bloemen-los-middel-roze.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item3": {
          model: "bloemen-los-groot-roze.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 936,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 7,
      offset: 5,
      children: {
        "bloemen-mix-item1": {
          model: "anemoon-los-blauw.1.glb",
          type3d: "Collada",
          scale: { x: 100, y: 100, z: 100 },
          dimensions: { x: 10.386275941691238, y: 9.17600825440787, z: 19.19674351997867 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 937,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 7,
      offset: 5,
      children: {
        "bloemen-mix-item1": {
          model: "anemoon-los-paars.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 938,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 7,
      offset: 5,
      children: {
        "bloemen-mix-item1": {
          model: "anemoon-los-rood.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 939,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 7,
      offset: 5,
      children: {
        "bloemen-mix-item1": {
          model: "anemoon-los-roze.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 940,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 7,
      offset: 5,
      children: {
        "bloemen-mix-item1": {
          model: "anemoon-los-wit.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 941,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 9,
      offset: 7,
      children: {
        "bloemen-mix-item1": {
          model: "ereprijs-los-lichtpaars.1.glb",
          type3d: "Collada",
          scale: { x: 100, y: 100, z: 100 },
          dimensions: {
            x: 12.202316972643715,
            y: 12.836749395200389,
            z: 32.79235092615504,
          },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 942,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 9,
      offset: 7,
      children: {
        "bloemen-mix-item1": {
          model: "ereprijs-los-paars.1.glb",
          type3d: "Collada",
          scale: { x: 100, y: 100, z: 100 },
          dimensions: {
            x: 12.202316972643715,
            y: 12.836749395200389,
            z: 32.79235092615504,
          },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 943,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 9,
      offset: 7,
      children: {
        "bloemen-mix-item1": {
          model: "ereprijs-los-roze.1.glb",
          type3d: "Collada",
          scale: { x: 100, y: 100, z: 100 },
          dimensions: {
            x: 12.202316972643715,
            y: 12.836749395200389,
            z: 32.79235092615504,
          },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 945,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 9,
      offset: 8,
      children: {
        "bloemen-mix-item1": {
          model: "geranium-los-paars.1.glb",
          type3d: "Collada",
          scale: { x: 50, y: 50, z: 50 },
          dimensions: {
            x: 14.670592285406466,
            y: 15.433357211513382,
            z: 39.42556250555765,
          },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 946,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 9,
      offset: 8,
      children: {
        "bloemen-mix-item1": {
          model: "geranium-los-rood.1.glb",
          type3d: "Collada",
          scale: { x: 50, y: 50, z: 50 },
          dimensions: {
            x: 14.670592285406466,
            y: 15.433357211513382,
            z: 39.42556250555765,
          },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 947,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 30,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 5,
      offset: 5,
      children: {
        "bloemen-mix-item1": {
          model: "lavendel-los-bruin.1.glb",
          type3d: "Collada",
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { x: 3.280102001215125, y: 5.740178502126469, z: 38.49890493546549 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
  {
    id: 958,
    params: {
      type3d: "SurfaceCollada",
      fill: 0,
      width: 0,
      height3d: 0,
      texture: "bloemenmixlicht.jpg",
      textureScale: 25,
      layer: 2,
      scale: { min: 80, max: 120 },
      rotation: { min: 0, max: 360 },
      spread: 7,
      offset: 7,
      children: {
        "bloemen-mix-item1": {
          model: "violen-los-klein-oranjerood.1.glb",
          type3d: "Collada",
          scale: { x: 50, y: 50, z: 50 },
          dimensions: { x: 9.008565048285764, y: 8.713409628964444, z: 34.54372532557038 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item2": {
          model: "violen-los-middel-oranjerood.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 25, y: 25, z: 25 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
        "bloemen-mix-item3": {
          model: "violen-los-groot-oranjerood.1.glb",
          type3d: "Collada",
          layer: 0,
          scale: { x: 30, y: 30, z: 30 },
          dimensions: { xo: 0, yo: 0, zo: 0, x: 0, y: 0, z: 0 },
          translation: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
        },
      },
    },
  },
];
